trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    docker build -t video-upload-service .
  displayName: 'Build Docker Image'

- task: Docker@2
  inputs:
    containerRegistry: '$(dockerRegistry)'
    repository: 'video-upload-service'
    command: 'push'
    tags: '$(Build.BuildId)'
