trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    docker build -t video-upload-service .
  displayName: 'Build Docker Image'

- task: Docker@2
  inputs:
    containerRegistry: '$(dockerRegistry)'
    repository: 'video-upload-service'
    command: 'push'
    tags: '$(Build.BuildId)'


- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    pip install locust
    locust -f locustfile.py --host=http://127.0.0.1:5000
  displayName: 'Exécuter les tests de charge Locust'

- script: |
    curl -LO https://github.com/jeremylong/DependencyCheck/releases/download/v6.0.2/dependency-check-6.0.2-release.zip
    unzip dependency-check-6.0.2-release.zip
    cd dependency-check
    ./bin/dependency-check.sh --project "Video Upload Project" --scan $(Build.SourcesDirectory)
  displayName: 'Exécuter OWASP Dependency-Check'

- script: |
    curl -LO https://github.com/jeremylong/DependencyCheck/releases/download/v6.0.2/dependency-check-6.0.2-release.zip
    unzip dependency-check-6.0.2-release.zip
    cd dependency-check
    ./bin/dependency-check.sh --project "Video Upload Project" --scan $(Build.SourcesDirectory)
  displayName: 'Exécuter OWASP Dependency-Check'
