apiVersion: v1
kind: Service
metadata:
  name: video-upload-service
spec:
  type: LoadBalancer
  selector:
    app: video-upload-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      



